import pizzaSrc from 'src/assets/images/pizaa-1.png';
import saladSrc from 'src/assets/images/salad-1.png';
import salmonSrc from 'src/assets/images/salmon.png';

export const mealsData = [
  {
    id: 1,
    calorie: 234,
    mealNumber: 1,
    category: 'pizza',
    imgUrl: pizzaSrc,
    alternatives: [2, 3],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Fajita Pizza Medium', ar: 'بيتزا فاهيتا متوسطة' },
  },
  {
    id: 2,
    calorie: 234,
    mealNumber: 2,
    category: 'salad',
    imgUrl: saladSrc,
    alternatives: [1, 3],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Quinoa Avocado Salad', ar: 'سلطة الكينوا والأفوكادو ' },
  },
  {
    id: 3,
    calorie: 234,
    mealNumber: 3,
    category: 'rice',
    imgUrl: salmonSrc,
    alternatives: [1, 2, 4, 5, 6, 7, 8],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Grilled Salmon', ar: 'سلمون مشوي' },
  },
  {
    id: 4,
    calorie: 234,
    mealNumber: 3,
    category: 'rice',
    imgUrl: salmonSrc,
    alternatives: [1, 2],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Grilled Salmon', ar: 'سلمون مشوي' },
  },
  {
    id: 5,
    calorie: 234,
    mealNumber: 3,
    category: 'rice',
    imgUrl: salmonSrc,
    alternatives: [1, 2],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Grilled Salmon', ar: 'سلمون مشوي' },
  },
  {
    id: 6,
    calorie: 234,
    mealNumber: 3,
    category: 'rice',
    imgUrl: salmonSrc,
    alternatives: [1, 2],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Grilled Salmon', ar: 'سلمون مشوي' },
  },
  {
    id: 7,
    calorie: 234,
    mealNumber: 3,
    category: 'rice',
    imgUrl: salmonSrc,
    alternatives: [1, 2],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Grilled Salmon', ar: 'سلمون مشوي' },
  },
  {
    id: 8,
    calorie: 234,
    mealNumber: 3,
    category: 'rice',
    imgUrl: salmonSrc,
    alternatives: [1, 2],
    macros: { pro: 10, carb: 10, fat: 10 },
    name: { en: 'Grilled Salmon', ar: 'سلمون مشوي' },
  },
];

export const foodCategories = [
  { id: 1, title: 'all', icon: 'solar:chef-hat-minimalistic-line-duotone' },
  { id: 2, title: 'salad', icon: 'fluent:bowl-salad-24-regular' },
  { id: 3, title: 'pizza', icon: 'ion:pizza-outline' },
  { id: 4, title: 'rice', icon: 'tdesign:rice' },
  { id: 5, title: 'pasta', icon: 'mdi:pasta' },
  { id: 6, title: 'burger', icon: 'majesticons:burger-line' },
  { id: 7, title: 'sadndwich', icon: 'game-icons:sandwich' },
  { id: 8, title: 'snacks', icon: 'ri:cake-3-fill' },
  { id: 9, title: 'drinks', icon: 'ri:drinks-2-line' },
];
